### ISSUE TITLE
Linux: failed to open libnvrtc-builtins.so.

### ISSUE THREAD

**Issue by menoos** [LuxCoreRender/BlendLuxCore#535]
**Environment:**
Linux, Manjaro (latest)
GPU Nvidia RTX2080TI, Driver 440.100
Blender 2.83.3
LuxCore 2.5 alpha0

**Steps to reproduce:**
1. Have a default cube scene
2. Set GPU API to CUDA and Film Device to GPU
3. Activate rendered view

**Actual Result:**
A "MergeSampleBuffersOCL CUDA program compilation error" is displayed.
Note: rendering on CPU with both CUDA and OPENCL works fine.
[log.txt](https://github.com/LuxCoreRender/LuxCore/files/5016669/log.txt)
![Screencast_CUDAerror](https://user-images.githubusercontent.com/69156458/89265580-01cc5300-d635-11ea-8ad2-7cca43440b3b.gif)

**Comment by Dade916** [comment]
The problem is here:

```
[LuxRays][82.053] [MergeSampleBuffersOCL] CUDA program compilation error: 
nvrtc: error: failed to open libnvrtc-builtins.so.
  Make sure that libnvrtc-builtins.so is installed correctly.
Traceback (most recent call last):
  File "/home/user/.config/blender/2.83/scripts/addons/BlendLuxCore/engine/base.py", line 123, in view_draw
    viewport.view_draw(self, context, depsgraph)
  File "/home/user/.config/blender/2.83/scripts/addons/BlendLuxCore/engine/viewport.py", line 221, in view_draw
    framebuffer.update(engine.session, scene)
  File "/home/user/.config/blender/2.83/scripts/addons/BlendLuxCore/draw/viewport.py", line 229, in update
    luxcore_session.GetFilm().GetOutputFloat(self._output_type, self.buffer)
```

BlendLuxCore is unable to find a library of NVIDIA runtime compiler (i.e. NVRTC). I should have fixed the problem with the patch listed above so the next automatic v2.5alpha0 build should work.

**Comment by Dade916** [comment]
Side note, if you install NVIDIA 450+ drivers, you will able to use hardware RTX acceleration and Optix denoiser:

```
[LuxRays][81.786] CUDA support: enabled
[LuxRays][81.786] CUDA support: available
[LuxRays][81.786] CUDA driver version: 10.20
[LuxRays][81.786] CUDA device count: 1
[LuxRays][81.786] Optix support: not available
```

Optix is not currently available and enabled in your installation.

**Comment by Theverat** [comment]
Thanks for the fix!

**Comment by Theverat** [comment]
Unfortunately, it looks like the fix is not working on my system (Ubuntu 20.04 with Nvidia driver 450.57).
I still get the same error:
```
nvrtc: error: failed to open libnvrtc-builtins.so.
  Make sure that libnvrtc-builtins.so is installed correctly.
```

**Comment by menoos** [comment]
Just checked and I get the same error.

**Comment by Dade916** [comment]
> Unfortunately, it looks like the fix is not working on my system (Ubuntu 20.04 with Nvidia driver 450.57).
> I still get the same error:
> 
> ```
> nvrtc: error: failed to open libnvrtc-builtins.so.
>   Make sure that libnvrtc-builtins.so is installed correctly.
> ```

Well, it is Python and BlendLuxCore, check why the code it isn't work on your system, does LoadLibrary call fails ? What paths are printed at the start ?
The patch was linked above: https://github.com/LuxCoreRender/BlendLuxCore/commit/e92b73646e745926ea1c27d34613967588ad5830

**Comment by Theverat** [comment]
I think this is the answer: https://stackoverflow.com/a/4326241

> To avoid having to set LD_LIBRARY_PATH, you modify the rpath entry in the .so files. On Linux, there are two utilities I found that do this: chrpath, and patchelf. chrpath is available from the Ubuntu repositories. It cannot change rpath on .so's that never had one. patchelf is more flexible.

> `patchelf --set-rpath ./ somelib.so` did the trick in fixing somelib.so that loads anotherlib.so that resides in the same path

**Comment by Theverat** [comment]
@menoos It should work now, can you test the latest daily build and report back if it's fine?

**Comment by menoos** [comment]
I did a fresh install of Blender to be sure that I didn't mess the plugin installation, but I get the same output.
Is there anything on top of console logs that I can do to make debugging easier? I'm not a power-user, but I can try.

**Comment by Theverat** [comment]
@meenos You don't need to provide any logs, I know the solution, I probably just forgot to add it to some packaging script.

**Comment by Theverat** [comment]
I'm at a loss a bit.
I inserted the fix here: https://github.com/LuxCoreRender/LinuxCompile/blob/master/nvrtc-install.sh
But looking at the azure output, an old version of this script is still used, and I don't know where/how to update it.

**Comment by Dade916** [comment]
For some reason, there were two copies of nvrtc-install.sh and you edited the one unused. The correct one was in distfiles directory. I should have fixed the problem and a new build is undergoing.

**Comment by Dade916** [comment]
The new builds are up.

**Comment by menoos** [comment]
No difference with the new build.
What has changed though, is that now selecting CUDA as GPU API makes my GPU selected automatically.
With previous builds, after selecting CUDA, my GPU was not available. I had to restart Blender to make it show up, and select it manually.

**Comment by DiracSea3921** [comment]
I have the same problem on the latest master branch. Is this issue solved or not? I tried patchelf command but it doesn't work.

**Comment by Theverat** [comment]
@DiracSea3921 Did you download the latest build from the release section? https://github.com/LuxCoreRender/BlendLuxCore/releases

> Is this issue solved or not?

It is solved, I forgot to close it.
If your problems persist with a build from the release section, please open a new issue with more details about the steps you've taken.

**Comment by johannes-wilde** [comment]
I still have this issue with the latest Build for Linux.
I am running PopOs 20.10 with Nvidia Driver 460.39 on an 2080ti

**Comment by menoos** [comment]
The same system and driver as Johannes, checked on 2080TI and 3090. The issue still occurs with 2.5RC1.

**Comment by johannes-wilde** [comment]
> The same system and driver as Johannes, checked on 2080TI and 3090. The issue still occurs with 2.5RC1.

Copy all files containing "libnvrtc" from home/.config/blender/yourblenderversion/scripts/addons/BlendLuxCore/bin to /usr/lib
Restart your PC. That should work.

**Comment by menoos** [comment]
Thanks Johannes, that worked.

**Comment by bogatkaj** [comment]
@Theverat Please add this to the wiki!

I searched the web for hours before I found this issue, which solves the problem for me
