### ISSUE TITLE
 I need help! I can't install Luxcorerender. gives an error message

### ISSUE THREAD

**Issue by LoudJoe** [LuxCoreRender/BlendLuxCore#878]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore-master\__init__.py", line 66, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.
You probably forgot to install one of the redistributable packages.
They are listed in the release announcement post.

ImportError: cannot import name 'pyluxcore' from 'BlendLuxCore-master.bin' (C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore-master\bin\__init__.py)

What to do ?

Will this render work on blender 4.0.2?

OS:  Windows 10
Blender version: 4.0.2
LuxCore version: 2.7

**Comment by LoudJoe** [comment]
I reinstalled but it still gives an error

**Comment by wizard3376** [comment]
I did everything you said but I get the following error

Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by odil24** [comment]
> Traceback (most recent call last):
>   File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
>     mod = importlib.import_module(module_name)
>   File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore-master\__init__.py", line 66, in <module>
>     raise Exception(msg + "\n\nImportError: %s" % error) from None
> Exception: 
> 
> Could not import pyluxcore.
> You probably forgot to install one of the redistributable packages.
> They are listed in the release announcement post.
> 
> ImportError: cannot import name 'pyluxcore' from 'BlendLuxCore-master.bin' (C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore-master\bin\__init__.py)
> 
> 
> What to do ?
> 
> Will this render work on blender 4.0.2?
> 
> OS:  Windows 10
> Blender version: 4.0.2
> LuxCore version: 2.7
> 

It will does not work until compiling under new version of Python 3.11 module for Blender 4.0.2, 4.0.3 or 4.1alpha

**Comment by LoudJoe** [comment]
@odil2 will LuxCore be compiled for the new Blender 4.0.3?

**Comment by Sharlybg** [comment]
> I did everything you said but I get the following error
> 
> Python: Traceback (most recent call last): File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\genericpath.py", line 19, in exists os.stat(path) TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

I'm using Blender 4.0.2  are you on the same version ?

**Comment by LoudJoe** [comment]
@Sharlybg Yes I have version 4.0.2

**Comment by wizard3376** [comment]
@SharlybgYes, I have blender version 4.0.2

**Comment by wizard3376** [comment]
@Sharlybg How did you install LuxCore in blender 4.0.2?

**Comment by wizard3376** [comment]
@Sharlybg, don't you have the same problems as me?
https://github.com/LuxCoreRender/BlendLuxCore/issues/875

**Comment by pbrt4bounty** [comment]
```It will does not work until compiling under new version of Python 3.11 module for Blender 4.0.2, 4.0.3 or 4.1alpha```
Blender 4.0.x series still uses Python 3.10. Only Blender 4.1 alpha uses Python 3.11 now

**Comment by odil24** [comment]
> Traceback (most recent call last): File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable mod = importlib.import_module(module_name) File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1050, in _gcd_import File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in _load_unlocked File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore-master__init__.py", line 66, in raise Exception(msg + "\n\nImportError: %s" % error) from None Exception:
> 
> Could not import pyluxcore. You probably forgot to install one of the redistributable packages. They are listed in the release announcement post.
> 
> ImportError: cannot import name 'pyluxcore' from 'BlendLuxCore-master.bin' (C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore-master\bin__init__.py)
> 
> What to do ?
> 
> Will this render work on blender 4.0.2?
> 
> OS: Windows 10 Blender version: 4.0.2 LuxCore version: 2.7

Download latest release: https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.8alpha1

**Comment by odil24** [comment]
@neo2068 close issue
