### ISSUE TITLE
BlendLuxCore v2.5 Blender 2.92 : Addon enable gives core dumped on Linux

### ISSUE THREAD

**Issue by johhnry** [LuxCoreRender/BlendLuxCore#670]
Hi,

### Steps to reproduce:

- Download fresh Blender 2.92.0 (02948a2cab44) and BlendLuxCore v2.5
- Enable the addon from the preferences > Addon tab

Blender just crash when I try to enable the addon.

### Error message from Blender console:

```shell
$ blender2.92                                                                                                                                                                josephhenry@pop-os
Writing userprefs: '/home/josephhenry/.config/blender/2.92/config/userpref.blend' ok
addon_utils.disable: BlendLuxCore not disabled
Modules Installed (BlendLuxCore) from '/home/josephhenry/Documents/blender/addons/BlendLuxCore-v2.5-linux64.zip' into '/home/josephhenry/.config/blender/2.92/scripts/addons'
Making LuxCore denoiser executable
[1]    15170 abort (core dumped)  /home/josephhenry/Documents/blender/bin/blender-2.92.0-linux64/blender
```
### Versions

OS: `Pop!_OS 20.10 x86_64`
Blender version: `Blender 2.92.0 (hash 02948a2cab44 built 2021-02-25 09:31:37)`
LuxCore version: `v2.5`

How can I investigate further more to determine the cause of the crash?

Thanks

Joseph

**Comment by Dade916** [comment]
Can you try if LuxMark works on your PC ?

And if the stand alone version (https://github.com/LuxCoreRender/LuxCore/releases/download/luxcorerender_v2.5/luxcorerender-v2.5-linux64.tar.bz2) works or prints an error ? Just run the test scene:

`./luxcoreui scenes/cornell/cornell.cfg`

**Comment by Fuzzillogic** [comment]
I have same issue since a week or two. It had worked fine with both BlendLuxCore v2.5 and Blender 2.92, and then it simply didn't anymore. I tried removing Blender's config to start from scratch. I purged the entire .cache directory. I just tried the 2.6 Alpha version. All simply `Aborted (core dumped)`.

The stand-alone version of LuxCoreRender works fine, renders without issues.

What *does* work: starting Blender with software OpenGL, thus using blender-softwaregl. Then, I can use BlendLuxCore without a problem! So, could this be something driver related? I'm using Kubuntu 21.04 now, X11, Mesa 21.0, Radeon RX550. Is there some residual configuration/setting that I could have missed in my cleaning-attempts?

**Comment by Fuzzillogic** [comment]
Forgot to mention: I initially used the [Blender flatpak](https://flathub.org/apps/details/org.blender.Blender). It is more isolated from the rest of the system. In this installation, I can install and enable BlendLuxCore 2.5, but when even when rendering the default cube using LuxCore I get this error: "MergeSampleBuffersOCL OpenCL program compilation error". But again, until recently it worked fine, albeit without hardware OpenCL.

Speaking of OpenCL: I had AMD's ROCm installed for hardware OpenCL, and yeah, it actually did work. Alas, not anymore, even though I haven't installed it anymore.

**Comment by johhnry** [comment]
Hi @Dade916 ,

I just tried running LuxMark v3.1 and the standalone LuxCore v2.5 programs and it works just fine without any crashes.

**Comment by Fuzzillogic** [comment]
FWI: my problem went away when using the new Blender 2.93 and latest BlendLuxCore release. I did had to manually install libtbb2. See #690.
