### ISSUE TITLE
Addon installation fail in Blender  2.92 & 2.93 - Linux

### ISSUE THREAD

**Issue by spellmell** [LuxCoreRender/BlendLuxCore#642]
Steps to reproduce:
Download the addons zip's and try to install

**BlendLuxCore-master**

Error message from Blender console:
Módulos instalados (BlendLuxCore-master) desde '/home/spellmell/Descargas/BlendLuxCore-master.zip' en '/home/spellmell/.config/blender/2.93/scripts/addons'
Traceback (most recent call last):
  File "/opt/blender-git/build_linux/bin/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/spellmell/.config/blender/2.93/scripts/addons/BlendLuxCore-master/__init__.py", line 63, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.

ImportError: cannot import name 'pyluxcore' from 'BlendLuxCore-master.bin' (/home/spellmell/.config/blender/2.93/scripts/addons/BlendLuxCore-master/bin/__init__.py)

---

**BlendLuxCore-v2.4-linux64**

Módulos instalados (BlendLuxCore) desde '/home/spellmell/Descargas/BlendLuxCore-v2.4-linux64.zip' en '/home/spellmell/.config/blender/2.93/scripts/addons'
Traceback (most recent call last):
  File "/opt/blender-git/build_linux/bin/2.93/scripts/modules/addon_utils.py", line 382, in enable
    mod.register()
  File "/home/spellmell/.config/blender/2.93/scripts/addons/BlendLuxCore/__init__.py", line 90, in register
    auto_load.register()
  File "/home/spellmell/.config/blender/2.93/scripts/addons/BlendLuxCore/auto_load.py", line 30, in register
    bpy.utils.register_class(cls)
ValueError: bpy_struct "LuxCoreLightProps" registration error: ies could not register

---

OS: 
Archlinux
Python 3.9.2

Blender version:
2.93.0 alpha master branch git
LuxCore version:
BlendLuxCore-master & BlendLuxCore-v2.4-linux64

Blender version:
community/blender 17:2.92.0-1
LuxCore version:
BlendLuxCore-master
In blender 2.92 of the community repo, BlendLuxCore-v2.4-linux64 can be installed.

**Comment by juangea** [comment]
It won't work in 2.93, 2.93 uses Python 3.9, 2.92 uses 3.7, that means that BlendLuxCore has to be compiled for Python 3.9 before it's compatible.
However 2.5 should be perfectly compatible with 2.92
I'm not sure about 2.4 since we don't use it anymore.

**Comment by Theverat** [comment]
Since you write "BlendLuxcore-master": you can't just clone the git repo and run it. You need to download one of the builds from the release section, otherwise the LuxCore binaries like pyluxcore.so will be missing.
Try the v2.5rc1 build in Blender 2.92, does it work?

In general, we don't support Blender versions that are unfinished (i.e. in alpha or beta phase).

**Comment by spellmell** [comment]
The good news is that the already compiled addon BlendLuxCore-v2.5rc1-linux64.zip can be installed without problems in blender 2.92 (not in 2.93). Although I haven't performed more than a single rendering test, everything seems to work fine.

Now I am trying to compile it according to the howto you have at:
https://wiki.luxcorerender.org/Compiling_LuxCore 
to find out if it is possible to make it work in blender 2.93 compiled with python 3.9.

In archlinux several of the dependencies that the first_run.sh script tries to install have a different name than in ubuntu, and after installing them the script gives several errors trying to find libraries, but after creating some symlinks finally they seem to be satisfied and the compilation can start. Unfortunately, it fails to finish correctly. I am trying to find out where the failure occurs.

I am going to close this thread because it is no longer a problem with the compiled addon. Thank you.
