### ISSUE TITLE
can't install on 3.0.1 due to error

### ISSUE THREAD

**Issue by jkerman2000** [LuxCoreRender/BlendLuxCore#778]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\dario\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlendLuxCore-master\__init__.py", line 66, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.
You probably forgot to install one of the redistributable packages.
They are listed in the release announcement post.

ImportError: cannot import name 'pyluxcore' from 'BlendLuxCore-master.bin' (C:\Users\dario\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlendLuxCore-master\bin\__init__.py)

**Comment by odil24** [comment]
> Traceback (most recent call last): File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable mod = **import**(module_name) File "C:\Users\dario\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlendLuxCore-master__init__.py", line 66, in raise Exception(msg + "\n\nImportError: %s" % error) from None Exception:
> 
> Could not import pyluxcore. You probably forgot to install one of the redistributable packages. They are listed in the release announcement post.
> 
> ImportError: cannot import name 'pyluxcore' from 'BlendLuxCore-master.bin' (C:\Users\dario\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlendLuxCore-master\bin__init__.py)

Hi. Works fine with Blender 3.3alpha and LuxCoreRender v2.61 (latest) from this:
https://github.com/LuxCoreRender/BlendLuxCore/releases/download/latest/BlendLuxCore-latest-win64.zip

Install it by copy/paste to "blender_version/scripts/addons/" not by "Install from ZIP".

**Comment by CodeFHD** [comment]
Closing this issue after a review with the following reasons/conclusions:
- Issue affected old Blender + LuxCore versions that are no longer supported
- Issue was missing information, no follow-up in 2 years

If you feel this issue is still relevant in 2025, please re-test it with a recent Blender + LuxCore version, then ask to reopen and provide the following information:
- Operating System
- CPU + GPU model
- Blender and LuxCoreRender version used for re-test
- Detailed steps how to reproduce the bug from an empty scene,
- provide a specific .blend-file
